src/seagulls/examples/_simple_rpg_background.py

Added GameBoard and Tile classes to capture if there are neighbor homes

---

src/seagulls/cli/_di_container.py
src/seagulls/examples/space_shooter/__init__.py
src/seagulls/examples/space_shooter/_asteroid_field.py
src/seagulls/examples/space_shooter/_ship.py
src/seagulls/examples/space_shooter/_shooter_scene.py
src/seagulls/examples/space_shooter/_space_collisions.py

Work in progress
-created a `SpaceCollision` class that will check for collisions and remove the laser and the rock
-need access to the list of laser and rock GameObjects

Basic rock and laser collisions

---

src/seagulls/examples/space_shooter/_space_collisions.py

Create scoreboard to track score by collision count

---

src/seagulls/examples/space_shooter/_asteroid_field.py
src/seagulls/examples/space_shooter/_space_collisions.py

Also fix bug where additional rocks spawn off screen

Add rock velocity and lose condition if rock reaches bottom of screen

---

src/seagulls/examples/space_shooter/_shooter_scene.py
src/seagulls/examples/space_shooter/_space_collisions.py

mostly trying to remove game rule logic from the space collisions class
- added an initial interface for defining game rules
- added rule class for rocks falling to the bottom of the screen
- added rule class for rock colliding with ship
- moved game-ending logic to the shooter scene class

initial refactor to move logic out of space collisions class

---

src/seagulls/examples/space_shooter/_asteroid_field.py
src/seagulls/examples/space_shooter/_ship.py

Remove y axis movement
Continuous rock respawn off screen

Space shooter tweaks

---

src/seagulls/cli/_di_container.py
src/seagulls/examples/space_shooter/__init__.py
src/seagulls/examples/space_shooter/_asteroid_field.py
src/seagulls/examples/space_shooter/_game_over_scene.py
src/seagulls/examples/space_shooter/_replay_shooter_button.py
src/seagulls/examples/space_shooter/_score_overlay.py
src/seagulls/examples/space_shooter/_score_tracker.py
src/seagulls/examples/space_shooter/_selectable_ship_menu.py
src/seagulls/examples/space_shooter/_shooter_scene.py

GameOverScene will display the game over and any additional buttons/actions the player can choose from. 
Adding buttons in progress

Add GameOverScene to handle when the space shooter ends

---

src/seagulls/examples/space_shooter/_space_collisions.py

Ensure rocks are only destroyed on-screen.

---

src/seagulls/examples/space_shooter/_asteroid_field.py

Ensure all rocks are within laser's reach on x axis

---

seagulls-space-shooter-demo/src/seagulls/space_shooter/_replay_shooter_button.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_selectable_ship_menu.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_blue_ship.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_empty_ship.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_orange_ship.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_replay_shooter_button.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_selectable_ship_menu.py

Add basic unit tests for a few classes

---

seagulls-space-shooter-demo/src/seagulls/space_shooter/_asteroid_field.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_asteroid_missed_rule.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_check_game_rules_interface.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_fit_to_screen.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_game_over_overlay.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_score_overlay.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_ship.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_ship_button.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_active_ship_client.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_asteroid_field.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_asteroid_missed_rule.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_cli_command.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_game_over_overlay.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_game_over_scene.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_replay_shooter_button.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_score_overlay.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_score_tracker.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_ship.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_ship_button.py

Adding additional tests for space_shooter classes

Add basic tests for space_shooter classes

---

seagulls-space-shooter-demo/src/seagulls/space_shooter/_selectable_ship_menu.py

Bug fix for the ship selection menu when replaying the game

Bug fix to replay Space Shooter game

---

seagulls-engine/src/seagulls/assets/_manager.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_laser.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_ship_powered_up_rule.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_space_collisions.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_space_rock.py

Lasers and space rocks are garbage collected to improve game performance

Address garbage collection for lasers and space rocks

---

seagulls-rpg-demo/src/seagulls/rpg_demo/_di_container.py
seagulls-rpg-demo/src/seagulls/rpg_demo/_fit_to_screen.py
seagulls-rpg-demo/src/seagulls/rpg_demo/_rpg_scene.py

Scale rpg game

---

seagulls-rpg-demo/src/seagulls/rpg_demo/_character.py
seagulls-rpg-demo/src/seagulls/rpg_demo/_di_container.py
seagulls-rpg-demo/src/seagulls/rpg_demo/_homes_and_trees.py
seagulls-rpg-demo/src/seagulls/rpg_demo/_rpg_background.py
seagulls-rpg-demo/src/seagulls/rpg_demo/_rpg_scene.py

Add collisions between character with trees and homes

Add collisions for character with trees and homes

---

seagulls-space-shooter-demo/src/seagulls/space_shooter/_di_container.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_ship_destroyed_rule.py
seagulls-space-shooter-demo/src/seagulls/space_shooter/_space_collisions.py
seagulls-space-shooter-demo/test/seagulls_test/space_shooter/test_space_collisions.py

Replace collision logic with pygame.Rect collisions

Replace collision logic with pygame.Rect collisions

---

seagulls-rpg-demo/src/seagulls/rpg_demo/_di_container.py
seagulls-rpg-demo/src/seagulls/rpg_demo/_rpg_scene_2.py

Fixed flake8 and mypy errors from previous commits

Fix flake8 and mypy errors

---

seagulls-rpg-demo/src/seagulls/rpg_demo/_rpg_scene_2.py

Ghost was walking off the screen unintentionally. Updated walking logic so this does not happen

Update walking logic for ghosts so it stays on the page

---

seagulls-rpg-demo/src/seagulls/rpg_demo/_di_container.py
seagulls-rpg-demo/src/seagulls/rpg_demo/_rpg_scene_2.py

When pumpkin and ghost collide, pumpkin turns into a real pumpkin and can no longer move

Add collision for pumpkin and ghost

---

seagulls-rpg-demo/src/seagulls/rpg_demo/_di_container.py
seagulls-rpg-demo/src/seagulls/rpg_demo/_rpg_scene_2.py

Adding "game over" text when the pumpkin runs into the ghost and the game ends

Add "game over" text for when pumpkin runs into the ghost

---

seagulls-rpg-demo/src/seagulls/rpg_demo/_di_container.py
seagulls-rpg-demo/src/seagulls/rpg_demo/_rpg_scene_2.py

Add sword throwing. If it hits a ghost, the ghost is removed

Add sword throwing 

---

seagulls-rpg-demo/src/seagulls/rpg_demo/_rpg_scene_2.py

Refactored tick() method and extracted methods

Refactoring to clean up methods

---

seagulls-rpg-demo/src/seagulls/rpg_demo/_rpg_scene_2.py

-Add additional logic for sword throwing
-Refactor pumpkin and sword movement

Add additional logic for sword throwing

---

seagulls-rpg-demo/src/seagulls/rpg_demo/_rpg_scene_2.py

Add logic to avoid losing health when the ghost is no longer alive

Ghost collision fixes

---

.github/workflows/cd.seagulls-rpg-demo.yml
.github/workflows/ci.yml
.github/workflows/ci_exe.yml

- generate artifacts for all our platforms any time we run a PR or main branch build
- ubuntu 22.04
- ubuntu 20.04
- macos 12
- windows 10
- create an unstable release when main branch builds
- create a stable release when a git tag is built
- push both stable and unstable releases to itch.io and make them installable independently

Build RPG EXE in new pipeline
